### PR TITLE
Add basic support for LaTeX builder

### LINKED ISSUE #11: make latexpdf throws error
Is it possible to include Lilypond output in a PDF generated by Sphinx? 

I have the following code in one of my `.rst` files

```
.. lily::
   :noedge:
   :nofooter:
   :audio:

   \version "2.20.0"
   \header {
   }
   \score {
   <<
      \new Staff \relative c' {
      \tempo 4 = 120
         c4 cis d ees e f fis g aes a bes b
   }
   >>
   }
```
and get the error `raise NotImplementedError(NotImplementedError: <class 'sphinx.writers.latex.LaTeXTranslator'> departing unknown node type: lily_outline_nod`. Is LaTeX conversion really not implemented yet or am I missing something?

### PR DESCRIPTION
**Pull request by SilverRainZ**
Close #11

### CODE REVIEW

**Comment by SilverRainZ** [comment]
Hello @fabianmoss, I just added a basic LaTeX support for this extension, can you please have a try? You can clone this branch and run make install to get it installed.

**Comment by fabianmoss** [comment]
It works like a charm! Thanks a lot. 
However, when I include a .ly file via `..lilyinclude::` (e.g. for making it playable in the html version), I get the following behavior:

```
.. lilyinclude:: ./lilypond/chromatic.ly
   :nofooter:
   :noedge:
   :audio: 
```
results in 

image

It seems that I need all three options for the snippet being displayed in the PDF, but I can't seem to hide the "audio option is supported for latex builder" message...

**Comment by SilverRainZ** [comment]
> It works like a charm! Thanks a lot. However, when I include a .ly file via `..lilyinclude::` (e.g. for making it playable in the html version), I get the following behavior:
> 
> ```
> .. lilyinclude:: ./lilypond/chromatic.ly
>    :nofooter:
>    :noedge:
>    :audio: 
> ```
> 
> results in
> 
> image
> 
> It seems that I need all three options for the snippet being displayed in the PDF, but I can't seem to hide the "audio option is supported for latex builder" message...

Ahhh... This is a typo, it should be "is *not* supported", remove the `:audio:` is fine for you, it is only available on HTML builder.

**Comment by fabianmoss** [comment]
Yes, I'll have a look at this next week.

**Pull request merged**
